-w-i-t-h- -o-p-e-n-(-'-r-e-p-l-_-n-e-t-s-e-c-.-t-x-t-'-,- -'-w-'-,- -e-n-c-o-d-i-n-g-=-'-u-t-f---8-'-,- -n-e-w-l-i-n-e-=-'-\-n-'-)- -a-s- -f-:-
- - - - -f-.-w-r-i-t-e-(-"-N-e-t-S-e-c-=-=->-L-e-g-a-c-y-\-n-"-)-
- - - - -f-.-w-r-i-t-e-(-"-n-e-t-s-e-c-=-=->-l-e-g-a-c-y-\-n-"-)-
- - - - -f-.-w-r-i-t-e-(-"-N-e-t-s-e-c-=-=->-L-e-g-a-c-y-\-n-"-)-
-